### ISSUE TITLE
Tracking of Fixed Assets in the ERP

### ISSUE THREAD

**Issue by adityaduggal** [adityaduggal/rigpl-erpnext#26]
Tracking of fixed assets in the erp is essential and needs to be linked to the Perpetual Inventory.

 - [ ] Create fixed assets item codes.
 - [ ] Try how to track serialized inventory like Cars, UPS, computers etc which also have warranties.
 - [ ] Check how would the monthly depreciation or annual depreciation would be calculated as per the depreciation app being made by a user on forums.

https://discuss.frappe.io/t/fixed-asset-depreciation/4308

**Comment by adityaduggal** [comment]
Completed in v7 of erpnext
